// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBeTNwdGTOKdoo4RSztMBTu8bFrWIHvrpw',
    appId: '1:646205136535:web:463745b940f38d04f453d2',
    messagingSenderId: '646205136535',
    projectId: 'flutter-remote-config-d45d3',
    authDomain: 'flutter-remote-config-d45d3.firebaseapp.com',
    storageBucket: 'flutter-remote-config-d45d3.firebasestorage.app',
    measurementId: 'G-NNXDHG12BR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZE4pWK2fPEJlWf0wQxSoaEhaIrNIZlag',
    appId: '1:646205136535:android:de09f7c94cd04c6cf453d2',
    messagingSenderId: '646205136535',
    projectId: 'flutter-remote-config-d45d3',
    storageBucket: 'flutter-remote-config-d45d3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA15ozaejQxkPRci8ZhIUCs1W12UXpMarU',
    appId: '1:646205136535:ios:14471156f92243f2f453d2',
    messagingSenderId: '646205136535',
    projectId: 'flutter-remote-config-d45d3',
    storageBucket: 'flutter-remote-config-d45d3.firebasestorage.app',
    iosBundleId: 'com.erazerdevs.firebaseRemoteConfig',
  );
}
